---
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  otlphttp/prom:
    endpoint: 'http://prometheus:9090/api/v1/otlp/'

  # otlphttp/mimir:
  #   endpoint: 'http://mimir:9009/otlp/'

  otlphttp/loki:
    endpoint: 'http://loki:3100/otlp/'

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [hostmetrics, otlp]
      processors: [batch]
      exporters: [otlphttp/prom]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/loki]
