global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      dc: 'prometheus'

storage:
  tsdb:
    out_of_order_time_window: 1m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
