FROM docker.io/golang:1.23-alpine as build

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64

COPY ./ /build
WORKDIR /build
RUN set -ex; apk add gcc make build-base
RUN go build -o app -ldflags="-s -w" .

FROM docker.io/alpine:3
RUN set -ex; adduser -D golang; mkdir /opt/app; chown -R golang /opt/app;
USER golang
EXPOSE 5001
COPY --from=build /build/app /opt/app/app
WORKDIR /opt/app
CMD ['app']
