FROM docker.io/php:8.3-alpine

RUN set -ex; \
    echo "@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories  ;\
    apk add php-sqlite3 php83-pecl-opentelemetry@testing ; \
    rm /var/cache/apk/*

RUN set -ex; \
    wget -O /usr/local/bin/composer https://getcomposer.org/download/2.8.1/composer.phar ; \
    chmod +x /usr/local/bin/composer

COPY . /opt
WORKDIR /opt

RUN set -ex; \
    composer install; \
    php artisan migrate --force;

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=5002"]
